<a href="https://colab.research.google.com/github/Chaudharysumit07/ChatBot-MirrorApp/blob/master/Assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np


In [23]:

def createFeatures( X ):
    return np.cumprod( np.flip( 2 * X - 1 , axis = 1 ), axis = 1 )



In [5]:
from scipy import linalg

In [8]:
def get_renamed(Y):
  return 2*Y-1

In [9]:
def get_features(X):
    X_new = createFeatures(X)
    a=linalg.khatri_rao(X_new,X_new).T
    f_vecs=linalg.khatri_rao(a,X_new).T
    return f_vecs

In [10]:
def Solver(X):
  return X.dot(w)

In [11]:
#STOCHASTIC GRADIENT DESCENT

In [12]:

def SGD():
  W0 =  100
  for i in range(1000):
    eta = 1 / (i+1000)
    

In [14]:
data_trn = np.genfromtxt('/content/train.dat')
data_tst = np.genfromtxt('/content/test.dat')

In [15]:
data_trn

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       ...,
       [1., 0., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 1., 1., ..., 0., 0., 1.]])

In [16]:
data_trn.shape

(10000, 9)

In [17]:
X_trn=createFeatures(data_trn[:,:-1])
Y_trn=get_renamed(data_trn[:,-1])

In [33]:
X_trn.shape

(10000, 8)

In [18]:
X_trn[0]

array([-1.,  1.,  1., -1.,  1., -1.,  1., -1.])

In [19]:
Y_trn

array([ 1., -1.,  1., ...,  1.,  1.,  1.])

In [29]:
from numpy import random
rndm=np.random.randint(X_trn.shape[0])
X_trn[rndm]
Y_trn[rndm]

-1.0

In [32]:

w = np.full((729,1),100)
for i in range(1000):
  eta = 1/(i+1000)
  for j in range(X_trn.shape[0]):
    rndm=np.random.randint(X_trn.shape[0])
    d_point=X_trn[rndm]
    label=Y_trn[rndm]

    if (1-label*(d_point.dot(w)) <= 0): # w input lena hai
      grdnt = w 
    else :
      grdnt = w - 100*d_point*label  # c hamara 100 hai   
    
    w_new = w - eta*grdnt


ValueError: ignored

In [ ]:
pred_y = X_trn.dot(w_new)

print(np.average(y_trn == pred_y))

In [ ]:
w = np.full((729,1),100)

In [ ]:
w.shape

(729, 1)

In [ ]:
w[0]

array([100])

In [ ]:
a=[]
for i in range(729):
    a.append(100)

a=np.array(a)    
  




In [ ]:
a.reshape(729,1)

array([[100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
      